### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by rpromyshlennikov**
There were several fixes and improvements in dependecies, so it would be better to keep them up to date.

### CODE REVIEW

**Comment by rpromyshlennikov** [comment]
Hi, @jimmypw,

thank you for such great library. Unfortunately I've coped with several issues:
1) it is not possible to request certificate in one specific environment, even if creds are ok, it's always "Access is denied due to invalid credentials" returned. It seems that it is fixed in https://github.com/Azure/go-ntlmssp/commit/5e29b886690f00c76b876ae9ab8e31e7c3509203, but I'm not sure for 100%. I'm going to check it later.
2)  there was impossible to set login in SAM format, e.g. "foobar", "RODION\\foobar", "rodion\\foobar", "rodion.home\\foobar" logins are ok, but not "foobar@rodion.home", it always returned the same "Access is denied due to invalid credentials" error. I have several integration tests and SAM format works at the moment. Seems it was fixed in https://github.com/Azure/go-ntlmssp/commit/cb9428e4ac1e1edffb49d21e3b29a0a30c664c83.

It would be very kind of you to review these changes. Thank you.

**Comment by jimmypw** [comment]
Hey, thank you for your contribution. Unfortunately I've not got an environment to test this any more.

The changes look fine, If I merge the changes in and cut a beta release would you mind testing it and get back to me with how you get on? If it's all good I'll bump it up to a full release.

**Comment by rpromyshlennikov** [comment]
> Hey, thank you for your contribution. Unfortunately I've not got an environment to test this any more.
> 
> The changes look fine, If I merge the changes in and cut a beta release would you mind testing it and get back to me with how you get on? If it's all good I'll bump it up to a full release.

No problem, I'll report you about any issue.

JFYI, I've already tested these changes for basic scenarios (with my Win2k12Server+AD+ADCS in single local VM), it (UPN logins and other forms of logins) works fine.
Also I've deployed to our stage area, when more mature prod-like testing infra (separate AD + separate Root CA + separate Issuer CA) is presented and I'm going to see results tomorrow.
What about the 1st issue, it's more difficult to test, because this issue is only in one environment with restricted access, I'll receive results later.

**Review by jimmypw — APPROVED** [review]
Looks great

**Comment by jimmypw** [comment]
Built and release created https://github.com/jimmypw/adcs/releases/tag/v1.2.1-beta1

**Comment by rpromyshlennikov** [comment]
Thank you.

**Comment by rpromyshlennikov** [comment]
Final report:
1) it works well with logins like: user@domain (new feature after this bump), user, domain\user, DOMAIN\user in my simple configuration and in staging prod-like one.
2) it doesn't fully solve the issue in one separate deployment with restricted access, but it WORKS when I provide creds in UPN format: user@domain, which was impossible before this patch. So at least I have a work around for now.

**Comment by jimmypw** [comment]
Cheers for getting back to me. Just a thought have you tried escaping that slash either by using single quotes

'domain\user'

Or by using double slash

"domain\\user"

**Comment by rpromyshlennikov** [comment]
> Just a thought have you tried escaping that slash either by using single quotes

Thank you for advice. 
Yep, it works fine in every other environment (If I use it as CLI with quotation or as library when slash escapes for me automatically), but in one restricted environment in works only in UPN format. Seems like magic to me. Unfortunately, I have no access to this environment to get root cause.

**Comment by jimmypw** [comment]
v1.2.1 uploaded as latest release.

**Pull request merged**
